org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true
unityStreamingAssets=
unityTemplateVersion=20
unityProjectPath=/Users/rajdeveloper/Downloads/mmo-ar-unity-develop
unity.projectPath=/Users/rajdeveloper/Downloads/mmo-ar-unity-develop
unity.debugSymbolLevel=none
unity.buildToolsVersion=35.0.0
unity.minSdkVersion=30
unity.targetSdkVersion=36
unity.compileSdkVersion=36
unity.applicationId=com.ultraverse
unity.abiFilters=armeabi-v7a,arm64-v8a
unity.versionCode=1
unity.versionName=1.0.0
unity.namespace=com.ultraverse
unity.agpVersion=8.7.2
unity.androidSdkPath=/Applications/Unity/Hub/Editor/6000.2.7f2/PlaybackEngines/AndroidPlayer/SDK
unity.androidNdkPath=/Applications/Unity/Hub/Editor/6000.2.7f2/PlaybackEngines/AndroidPlayer/NDK
unity.androidNdkVersion=27.2.12479018
unity.jdkPath=/Applications/Unity/Hub/Editor/6000.2.7f2/PlaybackEngines/AndroidPlayer/OpenJDK
unity.javaCompatabilityVersion=VERSION_17
unity.installInBuildFolder=false
android.useAndroidX=true
android.enableJetifier=true
android.bundle.includeNativeDebugMetadata=false
org.gradle.welcome=never